/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CSS3Logo: typeof import('./components/logos/CSS3Logo.vue')['default']
    CSSFeatureVideoContainer: typeof import('./components/CSSFeatureVideoContainer.vue')['default']
    GitHubLogo: typeof import('./components/logos/GitHubLogo.vue')['default']
    HTML5Logo: typeof import('./components/logos/HTML5Logo.vue')['default']
    JSLogo: typeof import('./components/logos/JSLogo.vue')['default']
    MyStory: typeof import('./components/MyStory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsComponent: typeof import('./components/SkillsComponent.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheMap: typeof import('./components/TheMap.vue')['default']
    TypeScriptLogo: typeof import('./components/logos/TypeScriptLogo.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    VueLogo: typeof import('./components/logos/VueLogo.vue')['default']
  }
}
